Compiled from "Collections.java"
public class java.util.Collections extends java.lang.Object{
    public static final java.util.Set EMPTY_SET;
    public static final java.util.List EMPTY_LIST;
    public static final java.util.Map EMPTY_MAP;
    public static void sort(java.util.List);
    public static void sort(java.util.List, java.util.Comparator);
    public static int binarySearch(java.util.List, java.lang.Object);
    public static int binarySearch(java.util.List, java.lang.Object, java.util.Comparator);
    public static void reverse(java.util.List);
    public static void shuffle(java.util.List);
    public static void shuffle(java.util.List, java.util.Random);
    public static void swap(java.util.List, int, int);
    public static void fill(java.util.List, java.lang.Object);
    public static void copy(java.util.List, java.util.List);
    public static java.lang.Object min(java.util.Collection);
    public static java.lang.Object min(java.util.Collection, java.util.Comparator);
    public static java.lang.Object max(java.util.Collection);
    public static java.lang.Object max(java.util.Collection, java.util.Comparator);
    public static void rotate(java.util.List, int);
    public static boolean replaceAll(java.util.List, java.lang.Object, java.lang.Object);
    public static int indexOfSubList(java.util.List, java.util.List);
    public static int lastIndexOfSubList(java.util.List, java.util.List);
    public static java.util.Collection unmodifiableCollection(java.util.Collection);
    public static java.util.Set unmodifiableSet(java.util.Set);
    public static java.util.SortedSet unmodifiableSortedSet(java.util.SortedSet);
    public static java.util.List unmodifiableList(java.util.List);
    public static java.util.Map unmodifiableMap(java.util.Map);
    public static java.util.SortedMap unmodifiableSortedMap(java.util.SortedMap);
    public static java.util.Collection synchronizedCollection(java.util.Collection);
    static java.util.Collection synchronizedCollection(java.util.Collection, java.lang.Object);
    public static java.util.Set synchronizedSet(java.util.Set);
    static java.util.Set synchronizedSet(java.util.Set, java.lang.Object);
    public static java.util.SortedSet synchronizedSortedSet(java.util.SortedSet);
    public static java.util.List synchronizedList(java.util.List);
    static java.util.List synchronizedList(java.util.List, java.lang.Object);
    public static java.util.Map synchronizedMap(java.util.Map);
    public static java.util.SortedMap synchronizedSortedMap(java.util.SortedMap);
    public static java.util.Collection checkedCollection(java.util.Collection, java.lang.Class);
    public static java.util.Set checkedSet(java.util.Set, java.lang.Class);
    public static java.util.SortedSet checkedSortedSet(java.util.SortedSet, java.lang.Class);
    public static java.util.List checkedList(java.util.List, java.lang.Class);
    public static java.util.Map checkedMap(java.util.Map, java.lang.Class, java.lang.Class);
    public static java.util.SortedMap checkedSortedMap(java.util.SortedMap, java.lang.Class, java.lang.Class);
    public static final java.util.Set emptySet();
    public static final java.util.List emptyList();
    public static final java.util.Map emptyMap();
    public static java.util.Set singleton(java.lang.Object);
    public static java.util.List singletonList(java.lang.Object);
    public static java.util.Map singletonMap(java.lang.Object, java.lang.Object);
    public static java.util.List nCopies(int, java.lang.Object);
    public static java.util.Comparator reverseOrder();
    public static java.util.Comparator reverseOrder(java.util.Comparator);
    public static java.util.Enumeration enumeration(java.util.Collection);
    public static java.util.ArrayList list(java.util.Enumeration);
    public static int frequency(java.util.Collection, java.lang.Object);
    public static boolean disjoint(java.util.Collection, java.util.Collection);
    public static boolean addAll(java.util.Collection, java.lang.Object[]);
    static boolean access$000(java.lang.Object, java.lang.Object);
    static {};
}

